[data.province]
filename_suffix = "province"
output_headers = ["code", "name"]
batch_size = 500

[data.regency]
filename_suffix = "regency"
output_headers = ["code", "province_code", "name"]
batch_size = 500

[data.district]
filename_suffix = "district"
output_headers = ["code", "regency_code", "name"]
batch_size = 1000

[data.village]
filename_suffix = "village"
output_headers = ["code", "district_code", "name"]
batch_size = 2000

[data.island]
filename_suffix = "island"
output_headers = [
  "code",
  "regency_code",
  "coordinate",
  "is_populated",
  "is_outermost_small",
  "name",
]
batch_size = 1000

[extractors]
fuzzy_threshold = 80.0
exclude_threshold = 65.0

[extractors.area]
code_keywords = ["kode"]
name_keywords = ["nama", "provinsi", "kabupaten", "kota", "kecamatan", "desa", "kelurahan"]
exclude_keywords = ["no", "ibukota", "jumlah penduduk", "penduduk", "ibu kota"]

[extractors.island]
code_keywords = ["kode", "pulau"]
name_keywords = ["nama", "pulau"]
coordinate_keywords = ["koordinat", "kordinat"]
status_keywords = ["bp/tbp", "bp", "tbp", "status", "keterangan"]
info_keywords = ["keterangan", "ket"]
exclude_keywords = ["no", "ibukota", "jumlah penduduk", "penduduk", "ibu kota"]
